"""empty message

Revision ID: ac8722c452c4
Revises: aeb8c800f471
Create Date: 2020-04-18 17:49:17.620560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8722c452c4'
down_revision = 'aeb8c800f471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_event_date'), 'event', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_date'), table_name='event')
    op.drop_column('event', 'date')
    # ### end Alembic commands ###
