"""empty message

Revision ID: b549c17bff07
Revises: 
Create Date: 2020-05-09 23:42:57.462968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b549c17bff07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogs',
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('dog_id')
    )
    op.create_index(op.f('ix_dogs_name'), 'dogs', ['name'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_enum', sa.Enum('TEST', 'OTHER', 'EAT', 'MEDICINE', 'CLOMIPRAMINE', 'TRIFEXIS', 'WALK', 'PLAY', 'TRAINING', 'BATH', 'GROOM', 'PEE', 'POOP', name='eventenum'), nullable=True),
    sa.Column('display', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('is_accident', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_table('assoc',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.dog_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assoc')
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dogs_name'), table_name='dogs')
    op.drop_table('dogs')
    # ### end Alembic commands ###
